Limit memory access of music playback to buffer dimensions
barsoosayque/libgdx-oboe pull request #21
Opened 2023-10-26 18:13 UTC by dasisdormax

This fixes a segfault that occurred when playing specific files.

In these cases, the playback would continue even after the file was ended. There, the library would play back the raw memory contents after the buffer, until eventually the app gets killed for illegal memory accesses.

2023-10-26 18:34 UTC, barsoosayque requested changes
Is there any reason for `int32_t` instead of unsigned ? Other than that, LGTM

2023-10-26 18:34 UTC, barsoosayque commented on library/src/cpp/audio/music.cpp
> +    auto iter_rem = m_main_pcm.end() - iter;
```suggestion
    auto iter_rem = std::distance(iter, m_main_pcm.end());
```

2023-10-26 18:34 UTC, barsoosayque commented on library/src/cpp/audio/music.cpp
> +        size = iter_rem;
```suggestion
    if (size > iter_rem) {
        size = iter_rem;
    }
```

2023-10-26 18:34 UTC, barsoosayque commented on library/src/cpp/audio/music.cpp
> +    int32_t frames_to_process = std::min((int32_t)frames, frames_in_pcm - m_current_frame);
```suggestion
    int32_t frames_to_process = std::min(static_cast<int32_t>(frames), frames_in_pcm - m_current_frame);
```

2023-10-26 18:41 UTC, dasisdormax commented
> Is there any reason for `int32_t` instead of unsigned ? Other than that, LGTM

Yep. `frames_in_pcm - m_current_frame` did end up less than zero.

I'll include your suggestions.

2023-10-26 19:50 UTC, barsoosayque commented
> Yep. `frames_in_pcm - m_current_frame` did end up less than zero.

Hmm. This is weird, but understandable for wacky android audio (or my half-hearted code). If I understand everything correctly, 
```c++
uint32_t frames_to_process = std::clamp(frames_in_pcm - m_current_frame, 0, frames);
```
should be a better solution ? We wouldn't want to play a negative amount of frames, but it's been awhile since I touched this code, may be wrong

2023-10-27 16:18 UTC, dasisdormax commented
The latest version works fine in my testing and still fixes the issue.

It uses clamp as suggested with signed integers as input, and uses the result ( > 0 ) as unsigned int.

2023-10-27 16:58 UTC, barsoosayque commented
Okay, looking good. Thank you !

2023-10-27 16:59 UTC, barsoosayque approved these changes

2023-10-27 16:59 UTC, merged